//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnChuyenNganh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietMatHang
    {
        public int MaChiTietMatHang { get; set; }
        public Nullable<int> MaKho { get; set; }
        public Nullable<int> MaMatHang { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
    
        public virtual Kho Kho { get; set; }
        public virtual MatHang MatHang { get; set; }
    }
}
