//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnChuyenNganh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Shipper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipper()
        {
            this.DonDatHangs = new HashSet<DonDatHang>();
        }

        public int MaShipper { get; set; }
        [Required(ErrorMessage = "Họ tên không được để trống")]
        public string HoTen { get; set; }
        public string SDT { get; set; }
        [Required(ErrorMessage = "Email không được để trống")]
        [EmailAddress(ErrorMessage = "Định dạng email không chính xác")]
        public string Email { get; set; }
        public Nullable<int> MaKho { get; set; }
        public Nullable<int> MaLoaiThanhVien { get; set; }
        public Nullable<int> MaCa { get; set; }
        public string DinhVi { get; set; }
        [Required(ErrorMessage = "Tên đăng nhập không được để trống")]
        public string TenDangNhap { get; set; }
        [Required(ErrorMessage = "Mật khẩu không được để trống")]
        public string MatKhau { get; set; }
        public Nullable<bool> DangDiGiao { get; set; }

        public virtual CaLam CaLam { get; set; }
        public string NhapLaiMatKhau { get; set; }
        public string NhapLaiMatKhauMoi { get; set; }
        public string MatKhauMoi { get; set; }
        public string MatKhauCu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatHang> DonDatHangs { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual LoaiThanhVien LoaiThanhVien { get; set; }
    }
}
