//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnChuyenNganh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipper()
        {
            this.DonDatHangs = new HashSet<DonDatHang>();
        }
    
        public int MaShipper { get; set; }
        public string HoTen { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public Nullable<int> MaKho { get; set; }
        public Nullable<int> MaLoaiThanhVien { get; set; }
        public Nullable<int> MaCa { get; set; }
        public string DinhVi { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public int SoDonHang { get; set; }
        public bool DangLam { get; set; }
        public virtual CaLam CaLam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatHang> DonDatHangs { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual LoaiThanhVien LoaiThanhVien { get; set; }
    }
}
